# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('royalty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('royalty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royalty.Royalty')),
            ],
            options={
                'verbose_name': 'Payee',
                'verbose_name_plural': 'Payees',
            },
        ),
    ]
