# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payees', '0002_auto_20180426_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='payee',
            name='payee_type',
            field=models.CharField(choices=[('singer', 'Singer'), ('author', 'Author'), ('company', 'Company')], default='singer', max_length=32, verbose_name='payee type'),
        ),
    ]
