# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('royalty', '0001_initial'),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Name')),
                ('author', models.CharField(max_length=256, verbose_name='Author')),
                ('singer', models.CharField(max_length=256, verbose_name='Singer')),
                ('play_time', models.DateTimeField(verbose_name='Play Time')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.Channel')),
                ('royalty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royalty.Royalty')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
    ]
